//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
namespace AssemblyCSharp
{
		public class Tile
		{
				Texture texture;
				int x{ get; set; }
				int y{ get; set; }
				public bool isEmpty{ get { return isEmpty; } set; }
				public Tile (Texture texture, int x, int y)
				{
						this.texture = texture;
						this.x = x;
						this.y = y;
				}
		}
}

